### ISSUE TITLE
myfile_subsample.avi is not produced by gui app

### ISSUE THREAD

**Issue by antonkulaga** [Tierpsy/tierpsy-tracker#56]
Despite what is written in output documentation I did not notice production of myfile_subsample.avi-like files by gui batch processing

**Comment by luigiferiani** [comment]
Hi @antonkulaga,

You're correct, the gui does not create a subsampled video by default, we need to update the docs.

To make tierpsy create the subsampled video, take your favourite parameters file, and edit it so that you specify the analysis points and place `VID_SUBSAMPLE` as the second item. 

For example, if you're using the TIERPSY analysis pipeline, the beginning of your json file should look like this:
```
{
    "analysis_type": "TIERPSY",
    "analysis_checkpoints": [
        "COMPRESS",
        "VID_SUBSAMPLE",
        "TRAJ_CREATE",
        "TRAJ_JOIN",
        "SKE_INIT",
        "BLOB_FEATS",
        "SKE_CREATE",
        "SKE_FILT",
        "SKE_ORIENT",
        "INT_PROFILE",
        "INT_SKE_ORIENT",
        "FEAT_INIT",
        "FEAT_TIERPSY"
    ],
```

If you want to create subsampled videos for data you've already processed, edit your parameters json as above, launch the `Bath Processing Multiple Files` GUI, and ask tierpsy to reanalyse using the edited json. Set `VID_SUBSAMPLE` to be the Analysis end point using the dropdown menu: Tierpsy should skip the `COMPRESSION` stage as it has already been done, and just perform the subsampling.

Let me know if this works for you
