### ISSUE TITLE
metaclass conflict

### ISSUE THREAD

**Issue by deligkarisk** [Tierpsy/tierpsy-tracker#93]
Hi,

I have managed to successfully install tierpsy-tracker in Ubuntu 22.04. I am trying to figure out how to use it with some sample videos we have.

However, when I click "Start" to run the batch processing I see the following output.
I was wondering if this is a bug or perhaps something I set-up incorrectly.

Any feedback would be appreciated.

```
Checking file 1 of 1. Total time: 0:00:00
*********************************************
Finished to check files.
Total time elapsed 0:00:00
*********************************************

*********************************************
Commands to be executed.
*********************************************
'/home/kosmas/miniconda3/envs/tierpsy/bin/python3.6' '/home/kosmas/repositories/tierpsy-tracker/tierpsy/processing/ProcessLocal.py' '/storage/other_trackings/celegans/test_approach/data/900 uL 24 well-777-996.avi' --masks_dir '/storage/other_trackings/celegans/test_approach/data/MaskedVideos' --results_dir '/storage/other_trackings/celeganss/test_approach/data/Results' --tmp_mask_dir '/home/kosmas/Tmp/MaskedVideos/' --tmp_results_dir '/home/kosmas/Tmp/Results/' --json_file '' --analysis_checkpoints 'COMPRESS' 'TRAJ_CREATE' 'TRAJ_JOIN' 'SKE_INIT' 'BLOB_FEATS' 'SKE_CREATE' 'SKE_FILT' 'SKE_ORIENT' 'INT_PROFILE' 'INT_SKE_ORIENT' 'FEAT_INIT' 'FEAT_TIERPSY'
*********************************************

*********************************************
Analysis Summary
*********************************************
1	Unprocessed files.
0	Files whose analysis is incompleted.
0	Invalid source files.
0	Files that were succesfully finished.
*********************************************
1	Total files to be processed.
*********************************************
Traceback (most recent call last):
  File "/home/kosmas/repositories/tierpsy-tracker/tierpsy/gui/AnalysisProgress.py", line 62, in run
    self.worker_fun(**self.worker_args)
  File "/home/kosmas/repositories/tierpsy-tracker/tierpsy/processing/processMultipleFilesFun.py", line 129, in processMultipleFilesFun
    is_debug = is_debug)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by WeheliyeHashi** [comment]
Could you send me your parameters file and video please. (weheliye@ic.ac.uk)

**Comment by deligkarisk** [comment]
Thank you @WeheliyeHashi for the feedback.

The issue was caused by some libraries incompatibility.

I re-did the installation with python 3.6  and the associated requirements file, and it now works just fine.

**Comment by monfort314** [comment]
Hi! Actually we experienced the same error, despite of having the right python version installed. 

This when following conda installation, in the step where we try to process batch, we get an error:

Traceback (most recent call last):
File "C:\Users\*\AppData\Local\anaconda3\envs\tierpsy\lib\site-packages\tierpsy\gui\AnalysisProgress.py", line 62, in run
self.worker_fun(**self.worker_args)
File "C:\Users\*\AppData\Local\anaconda3\envs\tierpsy\lib\site-packages\tierpsy\processing\processMultipleFilesFun.py", line 129, in processMultipleFilesFun
is_debug = is_debug)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Alternatively, when installing the environment from .yaml file 
conda env create -f tierpsy_tracker.yml


LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested torchvision 0.6.0**
  - package pytorch-1.5.0-cpu_py37h9f948e0_0 requires vc >=14.1,<15.0a0, but none of the providers can be installed
  
  We use Windows 10 and installation with Docker is not an option due to IT blockade.
